CLASS cl_dd_document DEFINITION PUBLIC.
  PUBLIC SECTION.
    METHODS add_link IMPORTING text TYPE any OPTIONAL url TYPE any OPTIONAL.
ENDCLASS.
CLASS cl_dd_document IMPLEMENTATION.
  METHOD add_link.
  ENDMETHOD.
ENDCLASS.
