CLASS cl_fp DEFINITION PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS get_reference RETURNING VALUE(r_ref) TYPE REF TO if_fp.
ENDCLASS.
CLASS cl_fp IMPLEMENTATION.
  METHOD get_reference.
  ENDMETHOD.
ENDCLASS.
